In [7]:
#lab08
import tensorflow as tf
import numpy as np
import pprint
pp = pprint.PrettyPrinter(indent=4)
sess = tf.InteractiveSession()

t = np.array([0., 1., 2., 3., 4., 5., 6.])
pp.pprint(t)
print(t.ndim) #몇 차원 array인가
print(t.shape) #이 array의 모양은 어떻게 생겼나?(7개의 element가 있으므로 7출력)
print(t[0], t[1], t[-1]) #indexing
print(t[2:5], t[4:-1])
print(t[:2], t[3:])

t = np.array([[1., 2., 3.], [4., 5., 6.], [7., 8., 9.], [10., 11., 12.]])
pp.pprint(t)
print(t.ndim) #2차원 array
print(t.shape) #행 4개, 열 3개(행렬)

array([0., 1., 2., 3., 4., 5., 6.])
1
(7,)
0.0 1.0 6.0
[2. 3. 4.] [4. 5.]
[0. 1.] [3. 4. 5. 6.]
array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [10., 11., 12.]])
2
(4, 3)


In [18]:
a = tf.constant([1,2,3,4]) #1차원 어레이 rank가 1이면 shape는[?]
tf.shape(a).eval() #element가 4개

array([4])

In [19]:
t = tf.constant([[1,2],
                 [3,4]]) #2차원 어레이, 각괄호가 몇 개있느냐가 rank임
tf.shape(t).eval() # (?,?)으로 출력, 행렬(2,2)가 나옴

array([2, 2])

In [20]:
t = tf.constant([[[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]],[[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]]]])
#rank: 각괄호가 4개 있으니까 4, (?,?,?,?)가 나옴
#맨 안의 각괄호의 element = 4, (?,?,?,4)
#그다음 안쪽 각괄호는 element = 3, (?,?,3,4)
#그다음은 element = 2, (?,2,3,4) 결국 (1,2,3,4)임
tf.shape(t).eval() 

array([1, 2, 3, 4])

In [21]:
[
    [
        [
            [1,2,3,4], 
            [5,6,7,8],
            [9,10,11,12]
        ],
        [
            [13,14,15,16],
            [17,18,19,20], 
            [21,22,23,24]
        ]
    ]
]

[[[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]],
  [[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]]]]

In [29]:
matrix1 = tf.constant([[1., 2.], [3., 4.]]) #각괄호 두개(2,2)
matrix2 = tf.constant([[1.], [2.]]) 
#각괄호 2개, 맨 바깥쪽 element수가 맨 앞에 위치하도록, 맨 안쪽 각괄호 element는 맨 뒤로: (2,1)
print('Matrix 1 shape', matrix1.shape)
print('Matrix 2 shape', matrix2.shape)
tf.matmul(matrix1, matrix2).eval()

Matrix 1 shape (2, 2)
Matrix 2 shape (2, 1)


array([[ 5.],
       [11.]], dtype=float32)

In [28]:
(matrix1*matrix2).eval() #matmul이랑 그냥 매트리스 곱하기랑은 완전히 다르다

array([[1., 2.],
       [6., 8.]], dtype=float32)

In [30]:
#broadcasting: shape이 다르더라도 연산을 가능하게 해준다
matrix1 = tf.constant([[3., 3.]])
matrix2 = tf.constant([[2.],[2.]])
(matrix1 + matrix2).eval() #두 매트리스를 더해줌

array([[5., 5.],
       [5., 5.]], dtype=float32)

In [31]:
#격이 맞지 않은 것을 맞추어줌
matrix1 = tf.constant([[1., 2.]])
matrix2 = tf.constant(3.) #[3., 3.]으로 만들어줌
(matrix1 + matrix2).eval()

array([[4., 5.]], dtype=float32)

In [33]:
matrix1 = tf.constant([[1., 2.]]) #rank가 다른 경우에도 연산가능
matrix2 = tf.constant([3.,4.])
(matrix1 + matrix2).eval()

array([[4., 6.]], dtype=float32)

In [34]:
matrix1 = tf.constant([[1., 2.]]) #extend해서
matrix2 = tf.constant([[3.],[4.]]) #extend 해서 연산
(matrix1 + matrix2).eval()

array([[4., 5.],
       [5., 6.]], dtype=float32)

In [35]:
tf.reduce_mean([1, 2], axis = 0).eval()
#평균을 줄여서 구한다. 행렬의 값을 줄여준다.
#integer가 된다.

1

In [40]:
x = [[1., 2.], 
    [3., 4.]]
#축이 0축과 1축이 있음. 열이 0축(axis = 0), 행이 1축(axis = 1)
tf.reduce_mean(x).eval()
#모두를 평균하여라

2.5

In [37]:
tf.reduce_mean(x, axis = 0).eval()
#axis를 0으로 만들어라, 열의 평균
#1열의 1.,3.의 평균->2.
#2열의 2.,4.의 평균->3.

array([2., 3.], dtype=float32)

In [39]:
tf.reduce_mean(x, axis = 1).eval()
#axis를 1로 만들어라, 행의 평균
#1행의 1.,2.의 평균->1.5
#2행의 3.,4.의 평균->3.5

array([1.5, 3.5], dtype=float32)

In [41]:
tf.reduce_mean(x, axis = -1).eval()
#axis = -1이면 가장 안쪽에 있는 것을 평균으로 넣어라
#가장 많이 사용

array([1.5, 3.5], dtype=float32)

In [42]:
x = [[1.,2.],
    [3.,4.]]
tf.reduce_sum(x).eval()

10.0

In [43]:
tf.reduce_sum(x, axis = 0).eval()

array([4., 6.], dtype=float32)

In [44]:
tf.reduce_sum(x, axis = -1).eval()

array([3., 7.], dtype=float32)

In [47]:
tf.reduce_mean(tf.reduce_sum(x, axis = -1)).eval()
#가장 안쪽의 축을 합하여 평균을 내라

5.0

In [49]:
x = [[0, 1, 2], #행이 axis =1, 열이 axis =0
    [2, 1, 0]]
tf.argmax(x, axis = 0).eval()
#axis = 0일때 가장 큰 수의 위치는 어디인가
#1열의 max인 argument = 1(맨 위의 행부터 0,1임)
#2열의 max인 argument = 0
#3열의 max인 argument = 0

array([1, 0, 0], dtype=int64)

In [51]:
tf.argmax(x, axis = 1).eval()
#axis = 1으로 했을 때(행을 기준으로 했을 때)
#0,1,2중 가장 큰 수는 2, 위치는 2
#2,1,0중 가장 큰 수는 2, 위치는 0

array([2, 0], dtype=int64)

In [52]:
tf.argmax(x, axis = -1).eval()
#맨 안쪽의 argmax

array([2, 0], dtype=int64)

In [54]:
#reshape 중요!
t = np.array([[[0, 1, 2], 
               [3, 4, 5]],
              
              [[6, 7, 8], 
               [9, 10, 11]]])
t.shape 
#각괄호 3개, rank = 3, (?,?,?)
#맨 안쪽 element수가 맨 뒤로 오도록 (?,?,3)
#다음 각괄호 element 수는 두번째, 그다음도, 그러면 (2,2,3)

(2, 2, 3)

In [55]:
tf.reshape(t, shape = [-1, 3]).eval()
#아래의 형태로 나누고 싶다.
#안에 것은 3, 나머지는 알아서해(-1)
#rank가 3개인데 2개로 주고 싶다

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [56]:
tf.reshape(t, shape = [-1, 1, 3]).eval()
#조합은 그대로 가져가면서 shape만 바뀌므로 섞이지는 않는다.
#전체의 shape를 조정
#rank를 늘리고 싶은 경우 shape에 하나 더 추가

array([[[ 0,  1,  2]],

       [[ 3,  4,  5]],

       [[ 6,  7,  8]],

       [[ 9, 10, 11]]])

In [57]:
#reshape(squeeze,expand)
tf.squeeze([[0],[1],[2]]).eval()
#각괄호가 많을 때 펴줌 하나로

array([0, 1, 2])

In [58]:
tf.expand_dims([0,1,2], 1).eval()
#dimension을 추가하고 싶을 때
#얼마를 expand할 것인가->1

array([[0],
       [1],
       [2]])

In [62]:
t = tf.one_hot([[0],[1],[2],[0]], depth = 3).eval()
#맨처음 [0]은 0번째 인덱스만 1이 된다. [1., 0., 0.]
#두번째 [1]은 1번째 인덱스만 1이 된다. [0., 1., 0]
#이런식으로 벡터로 만들어줌
#rank를 하나 더 expand해줌, 위는 각괄호가 2개인데 3개로 늘어남
#이런 경우 expand한 게 싫다면 reshape를 해주면 된다.
tf.reshape(t, shape = [-1, 3]).eval()

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.]], dtype=float32)

In [64]:
#casting int로 변경하고 싶을 때, true->1, false->0으로 적고 싶을 때
tf.cast([1.8, 2.2, 3.3, 4.9], tf.int32).eval()

array([1, 2, 3, 4])

In [65]:
tf.cast([True, False, 1 == 1, 0 == 1], tf.int32).eval()
#0,1의 값으로 변경이 됐다.
#true인 경우를 다 더하고 싶을 경우 등에 사용한다

array([1, 0, 1, 0])

In [66]:
#stack, 쌓는다
x = [1, 4]
y = [2, 5]
z = [3, 6]

tf.stack([x, y, z]).eval()
#쌓아줍니다

array([[1, 4],
       [2, 5],
       [3, 6]])

In [67]:
tf.stack([x, y, z], axis = 1).eval()

array([[1, 2, 3],
       [4, 5, 6]])

In [68]:
tf.stack([x, y, z], axis = 0).eval()

array([[1, 4],
       [2, 5],
       [3, 6]])

In [69]:
tf.stack([x, y, z], axis = -1).eval()

array([[1, 2, 3],
       [4, 5, 6]])

In [70]:
#ones zeros like
#이거랑 모양이 똑같은 것으로 0이나 1로 체워진 텐서를 만들고 싶을때
x = [[0, 1, 2], #행이 axis =1, 열이 axis =0
    [2, 1, 0]]
tf.ones_like(x).eval()

array([[1, 1, 1],
       [1, 1, 1]])

In [71]:
tf.zeros_like(x).eval()

array([[0, 0, 0],
       [0, 0, 0]])

In [75]:
#zip
for x, y in zip([1,2,3], [4,5,6]):
    print(x, y)

print('\n')

for x, y, z in zip([1,2,3], [4,5,6], [7,8,9]):
    print(x, y, z)

1 4
2 5
3 6


1 4 7
2 5 8
3 6 9


In [96]:
#transpose
t = np.array([[[0, 1, 2, 3], [4, 5, 6, 7], [8, 9, 10, 11]], [[12, 13, 14, 15], [16, 17, 18, 19], [20, 21, 22, 23]]])
pp.pprint(t.shape)
pp.pprint(t)

(2, 3, 4)
array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])


In [97]:
t1 = tf.transpose(t, [1,0,2]) #(2,3,4)를 index(1,0,2)순서로 바꾸겠다->(3,2,4)
pp.pprint(sess.run(t1).shape)
pp.pprint(sess.run(t1))

(3, 2, 4)
array([[[ 0,  1,  2,  3],
        [12, 13, 14, 15]],

       [[ 4,  5,  6,  7],
        [16, 17, 18, 19]],

       [[ 8,  9, 10, 11],
        [20, 21, 22, 23]]])


In [99]:
t2 = tf.transpose(t, [1,2,0]) #(2,3,4)->(3,4,2)
pp.pprint(sess.run(t2).shape)
pp.pprint(sess.run(t2))

(3, 4, 2)
array([[[ 0, 12],
        [ 1, 13],
        [ 2, 14],
        [ 3, 15]],

       [[ 4, 16],
        [ 5, 17],
        [ 6, 18],
        [ 7, 19]],

       [[ 8, 20],
        [ 9, 21],
        [10, 22],
        [11, 23]]])


In [100]:
t3 = tf.transpose(t, [2,1,0]) #원래는(2,3,4)->(4,3,2)
pp.pprint(sess.run(t3).shape)
pp.pprint(sess.run(t3))

(4, 3, 2)
array([[[ 0, 12],
        [ 4, 16],
        [ 8, 20]],

       [[ 1, 13],
        [ 5, 17],
        [ 9, 21]],

       [[ 2, 14],
        [ 6, 18],
        [10, 22]],

       [[ 3, 15],
        [ 7, 19],
        [11, 23]]])


In [102]:
t4= tf.transpose(t, [2,0,1]) #원래는(2,3,4)->(4,2,3)
pp.pprint(sess.run(t4).shape)
pp.pprint(sess.run(t4))

(4, 2, 3)
array([[[ 0,  4,  8],
        [12, 16, 20]],

       [[ 1,  5,  9],
        [13, 17, 21]],

       [[ 2,  6, 10],
        [14, 18, 22]],

       [[ 3,  7, 11],
        [15, 19, 23]]])
