In [6]:
#lab04-01
import tensorflow as tf

x1_data = [73., 93., 89., 96., 73.]
x2_data = [80., 88., 91., 98., 66.]
x3_data = [75., 93., 90., 100., 70.]
y_data = [152., 185., 180., 196., 142.]
#x input이 3개, instance가 여러개 나왔을 경우 y의 값을 예측해보자.

x1 = tf.placeholder(tf.float32) #tf.float: data type
#placeholder: 실행시키는 단계에서 값을 넣어주고 싶을 때 사용
x2 = tf.placeholder(tf.float32)
x3 = tf.placeholder(tf.float32)
Y = tf.placeholder(tf.float32)

w1 = tf.Variable(tf.random_normal([1]), name = 'weight1') #weight는 하나의 값
w2 = tf.Variable(tf.random_normal([1]), name = 'weight2')
w3 = tf.Variable(tf.random_normal([1]), name = 'weight3')
b = tf.Variable(tf.random_normal([1]), name = 'bias')
hypothesis = x1*w1 + x2*w2 + x3*w3 + b

cost = tf.reduce_mean(tf.square(hypothesis - Y)) #hypothesis와 Y의 차의 제곱
optimizer = tf.train.GradientDescentOptimizer(learning_rate = 1e-5)
train = optimizer.minimize(cost) #cost가 가장 작게 optimize

sess = tf.Session()
sess.run(tf.global_variables_initializer()) #세션을 초기화 하는 순간 변수 W에 그 값이 지정
#변수들을 global_variables_initializer() 를 이용해서 초기화 한후, 초기화된 결과를 세션에 전달해 줘야 한다.

for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train],
                    feed_dict = {x1: x1_data, x2: x2_data, x3: x3_data, Y: y_data})
                    #feed_dict에는 맨 위의 데이터 값을 주겠다. Y=우리가 목표로 하는 값
#feed_dict 변수를 이용해서 플레이스홀더 x에 위의 data를 피드하면, 
#세션에 의해서 그래프가 실행되면서 x는 feed_dict에 의해서 정해진 피드 데이터를 하나씩 읽어서 실행한다.

    if step % 10 == 0:
        print(step, "Cost:", cost_val, '\nPrediction\n', hy_val)

0 Cost: 1859.4375 
Prediction
 [123.92025 132.30174 139.0476  150.8921   97.05795]
10 Cost: 55.88088 
Prediction
 [161.45663 177.47209 183.52644 199.33134 131.52272]
20 Cost: 55.565685 
Prediction
 [161.54155 177.62845 183.65231 199.47125 131.65309]
30 Cost: 55.26853 
Prediction
 [161.51323 177.64854 183.64397 199.46503 131.67952]
40 Cost: 54.973053 
Prediction
 [161.48463 177.66817 183.63524 199.4584  131.70555]
50 Cost: 54.67907 
Prediction
 [161.45612 177.68776 183.62656 199.45178 131.73152]
60 Cost: 54.38674 
Prediction
 [161.42769 177.70729 183.6179  199.44519 131.75743]
70 Cost: 54.096107 
Prediction
 [161.39935 177.72675 183.60924 199.43863 131.78326]
80 Cost: 53.806957 
Prediction
 [161.37105 177.74617 183.60062 199.43207 131.80899]
90 Cost: 53.519306 
Prediction
 [161.34283 177.76552 183.59201 199.4255  131.83469]
100 Cost: 53.233204 
Prediction
 [161.31473 177.78485 183.58344 199.41898 131.86032]
110 Cost: 52.948677 
Prediction
 [161.28667 177.80411 183.57487 199.41246 131.88

1100 Cost: 31.205517 
Prediction
 [158.85611 179.47357 182.8342  198.84491 134.10356]
1110 Cost: 31.039942 
Prediction
 [158.83476 179.48827 182.8277  198.83989 134.1231 ]
1120 Cost: 30.87531 
Prediction
 [158.81345 179.50288 182.82121 198.8349  134.14256]
1130 Cost: 30.711573 
Prediction
 [158.7922  179.51747 182.81474 198.82988 134.16197]
1140 Cost: 30.54869 
Prediction
 [158.77103 179.53203 182.8083  198.8249  134.18135]
1150 Cost: 30.386738 
Prediction
 [158.74991 179.54654 182.80186 198.81992 134.20065]
1160 Cost: 30.225561 
Prediction
 [158.72882 179.56102 182.79544 198.81496 134.21991]
1170 Cost: 30.065292 
Prediction
 [158.70781 179.57545 182.78905 198.81003 134.23914]
1180 Cost: 29.90589 
Prediction
 [158.68686 179.58986 182.78265 198.80511 134.2583 ]
1190 Cost: 29.747364 
Prediction
 [158.66595 179.60422 182.7763  198.80019 134.2774 ]
1200 Cost: 29.589685 
Prediction
 [158.64511 179.61853 182.76996 198.79527 134.29646]
1210 Cost: 29.432907 
Prediction
 [158.62434 179.63281 18

In [8]:
import tensorflow as tf

x_data = [[73., 80., 75.], 
          [93., 88., 93.], 
          [89., 91., 90.], 
          [96., 98., 100.],
          [73., 66., 70.]]
y_data = [[152.], [185.], [180.], [196.], [142.]]
#vector형식으로 저장

X = tf.placeholder(tf.float32, shape = [None, 3]) #x1,x2,x3의 세 개가 들어감, 각 element가 가지는 값은 3개
Y = tf.placeholder(tf.float32, shape = [None, 1]) #결과는 하나
#x_data는 이 데이터(인스턴스)가 몇개냐 하는건데 지금은 5개지만 그 이상일 수 있음
#따라서 n개를 가질 것이라서 None으로 적은 것임

W = tf.Variable(tf.random_normal([3,1]), name = 'weight')
b = tf.Variable(tf.random_normal([1]), name = 'bias')

hypothesis = tf.matmul(X, W) + b
cost = tf.reduce_mean(tf.square(hypothesis - Y))
optimizer = tf.train.GradientDescentOptimizer(learning_rate = 1e-5)
train = optimizer.minimize(cost)

sess = tf.Session()
sess.run(tf.global_variables_initializer())

for step in range(2001):
    cost_val, hy_val, _ = sess.run(
    [cost, hypothesis, train], feed_dict = {X: x_data, Y: y_data})
    
    if step % 10 == 0:
        print(step, 'Cost: ', cost_val, '\nPrediction\n', hy_val)

0 Cost:  26394.215 
Prediction
 [[ 6.3242455]
 [11.946863 ]
 [ 9.403257 ]
 [11.252411 ]
 [ 9.458151 ]]
10 Cost:  1.0149076 
Prediction
 [[150.04086]
 [184.68108]
 [179.60252]
 [196.59464]
 [141.21068]]
20 Cost:  0.77256644 
Prediction
 [[150.47699]
 [185.20285]
 [180.11792]
 [197.1554 ]
 [141.60849]]
30 Cost:  0.77184445 
Prediction
 [[150.4796 ]
 [185.2036 ]
 [180.11993]
 [197.15706]
 [141.60887]]
40 Cost:  0.77112937 
Prediction
 [[150.4809 ]
 [185.20276]
 [180.12039]
 [197.15704]
 [141.60806]]
50 Cost:  0.7704023 
Prediction
 [[150.4822 ]
 [185.20189]
 [180.12082]
 [197.157  ]
 [141.60722]]
60 Cost:  0.7696906 
Prediction
 [[150.48347]
 [185.20105]
 [180.12125]
 [197.15697]
 [141.60641]]
70 Cost:  0.76898086 
Prediction
 [[150.48476]
 [185.20018]
 [180.12169]
 [197.15694]
 [141.60559]]
80 Cost:  0.76826984 
Prediction
 [[150.48605]
 [185.19939]
 [180.12215]
 [197.15692]
 [141.60481]]
90 Cost:  0.7675619 
Prediction
 [[150.48734]
 [185.19852]
 [180.12257]
 [197.15689]
 [141.60399]]
1

920 Cost:  0.71672803 
Prediction
 [[150.58342]
 [185.13554]
 [180.15569]
 [197.15227]
 [141.54546]]
930 Cost:  0.7161895 
Prediction
 [[150.58447]
 [185.13486]
 [180.15604]
 [197.15219]
 [141.54486]]
940 Cost:  0.715673 
Prediction
 [[150.58551]
 [185.13419]
 [180.15642]
 [197.15213]
 [141.54425]]
950 Cost:  0.7151405 
Prediction
 [[150.58655]
 [185.1335 ]
 [180.15677]
 [197.15204]
 [141.54364]]
960 Cost:  0.7146141 
Prediction
 [[150.58759]
 [185.13281]
 [180.15714]
 [197.15196]
 [141.54305]]
970 Cost:  0.71407455 
Prediction
 [[150.58864]
 [185.13213]
 [180.15749]
 [197.15187]
 [141.54243]]
980 Cost:  0.7135583 
Prediction
 [[150.58966]
 [185.13145]
 [180.15784]
 [197.1518 ]
 [141.54184]]
990 Cost:  0.7130366 
Prediction
 [[150.59068]
 [185.13078]
 [180.1582 ]
 [197.1517 ]
 [141.54124]]
1000 Cost:  0.7125221 
Prediction
 [[150.59172]
 [185.13013]
 [180.15857]
 [197.15164]
 [141.54065]]
1010 Cost:  0.71200883 
Prediction
 [[150.59273]
 [185.12944]
 [180.15892]
 [197.15155]
 [141.5400

 [[150.66939]
 [185.0797 ]
 [180.18596]
 [197.14351]
 [141.4981 ]]
1840 Cost:  0.67378104 
Prediction
 [[150.67024]
 [185.07916]
 [180.18626]
 [197.14339]
 [141.49765]]
1850 Cost:  0.67336166 
Prediction
 [[150.6711 ]
 [185.0786 ]
 [180.18657]
 [197.14326]
 [141.49722]]
1860 Cost:  0.6729578 
Prediction
 [[150.67194]
 [185.07806]
 [180.18686]
 [197.14316]
 [141.4968 ]]
1870 Cost:  0.67255926 
Prediction
 [[150.67278]
 [185.07751]
 [180.18718]
 [197.14305]
 [141.49635]]
1880 Cost:  0.6721519 
Prediction
 [[150.67361]
 [185.07697]
 [180.18747]
 [197.14293]
 [141.49591]]
1890 Cost:  0.6717452 
Prediction
 [[150.67445]
 [185.07642]
 [180.18776]
 [197.1428 ]
 [141.49547]]
1900 Cost:  0.671343 
Prediction
 [[150.6753 ]
 [185.0759 ]
 [180.18808]
 [197.1427 ]
 [141.49506]]
1910 Cost:  0.6709391 
Prediction
 [[150.67615]
 [185.07538]
 [180.18839]
 [197.14261]
 [141.49464]]
1920 Cost:  0.67053145 
Prediction
 [[150.67697]
 [185.07481]
 [180.18867]
 [197.14247]
 [141.49422]]
1930 Cost:  0.6701321

In [1]:
#lab04-02
#data가 너무 많아지는 경우는 텍스트 파일로 저장
import tensorflow as tf
import numpy as np
tf.set_random_seed(777)

xy = np.loadtxt('data-01-test-score.csv', delimiter = ',', dtype = np.float32)
#전체를 어레이로 읽어옴
x_data = xy[:, 0:-1] #slicing, [:,2]앞에 있는 값이 row, 두번째가 2번째 인덱스
#전체 row, 열은 0:-1까지(0부터 맨 마지막 인덱스 앞 인덱스까지)
y_data = xy[:, [-1]]
#전체 n개 다 가져온다, 맨 마지막 끝에 열만 가져오겠다.

print(x_data.shape, x_data, len(x_data))
print(y_data.shape, y_data)
#shape이 맞는지를 확인 후 출력하기

X = tf.placeholder(tf.float32, shape=[None, 3]) 
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([3,1]), name = 'weight')
#3개가 들어와서 1개의 y값이 나간다.[들어오는 값, 나가는 값]
b = tf.Variable(tf.random_normal([1]), name = 'bias')
#출력 y값은 하나[나가는 값]

hypothesis = tf.matmul(X, W) + b
cost = tf.reduce_mean(tf.square(hypothesis - Y))

optimizer = tf.train.GradientDescentOptimizer(learning_rate = 1e-5)
train = optimizer.minimize(cost)

sess = tf.Session()
sess.run(tf.global_variables_initializer())

for step in range(2001):
    cost_val, hy_val, _ = sess.run(
        [cost, hypothesis, train],
        feed_dict = {X: x_data, Y: y_data})

#새 데이터 예측
print("Your score will be ", sess.run(hypothesis,
                        feed_dict = {X: [[100,70,101]]}))
print("Other scores will be ", sess.run(hypothesis,
                        feed_dict = {X: [[60,70,110], [90,100,80]]}))

C:\Users\ehrme\AppData\Local\Continuum\anaconda3\envs\sugyeong_2019\lib\site-packages\numpy\_distributor_init.py:32: UserWarning: loaded more than 1 DLL from .libs:
C:\Users\ehrme\AppData\Local\Continuum\anaconda3\envs\sugyeong_2019\lib\site-packages\numpy\.libs\libopenblas.IPBC74C7KURV7CB2PKT5Z5FNR3SIBV4J.gfortran-win_amd64.dll
C:\Users\ehrme\AppData\Local\Continuum\anaconda3\envs\sugyeong_2019\lib\site-packages\numpy\.libs\libopenblas.TXA6YQSD3GCQQC22GEQ54J2UDCXDXHWN.gfortran-win_amd64.dll
  stacklevel=1)
C:\Users\ehrme\AppData\Local\Continuum\anaconda3\envs\sugyeong_2019\lib\site-packages\tensorflow\python\framework\dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\Users\ehrme\AppData\Local\Continuum\anaconda3\envs\sugyeong_2019\lib\site-packages\tensorflow\python\framework\dtypes.py:517: FutureWarning: Pass

(5, 3) [[73. 80. 75.]
 [93. 88. 93.]
 [89. 91. 90.]
 [73. 66. 70.]
 [53. 46. 55.]] 5
(5, 1) [[152.]
 [185.]
 [180.]
 [142.]
 [101.]]
Your score will be  [[171.88803]]
Other scores will be  [[106.04587]
 [196.89703]]


In [27]:
import tensorflow as tf

filename_queue = tf.train.string_input_producer(
['data-01-test-score.csv'], shuffle=False, name = 'filename_queue')
#file이 너무 큰 경우, file을 만들어서 queue

reader = tf.TextLineReader()
key, value = reader.read(filename_queue)
#reader를 정의하는 부분

record_defaults = [[0.], [0.], [0.], [0.]] #각 필드의 데이터 타입
#디폴트 value는 빈 column.
xy = tf.decode_csv(value, record_defaults = record_defaults)
#csv로 decode하라

train_x_batch, train_y_batch = tf.train.batch([xy[0:-1], xy[-1:]], batch_size = 10)
#pump로 데이터를 빨아올리듯이 가져온다. 한 번 펌프할 때마다 10개씩 가져와라

X = tf.placeholder(tf.float32, shape=[None, 3])#x value의 개수
Y = tf.placeholder(tf.float32, shape=[None, 1])#y value의 개수

W = tf.Variable(tf.random_normal([3,1]),name = 'weight')
b = tf.Variable(tf.random_normal([1]), name = 'bias')

hypothesis = tf.matmul(X, W) + b
cost = tf.reduce_mean(tf.square(hypothesis - Y))
optimizer = tf.train.GradientDescentOptimizer(learning_rate = 1e-5)
train = optimizer.minimize(cost)

sess = tf.Session()
sess.run(tf.global_variables_initializer())

coord = tf.train.Coordinator()
threads = tf.train.start_queue_runners(sess=sess, coord=coord)

for step in range(2001):
    x_batch, y_batch = sess.run([train_x_batch, train_y_batch])
    cost_val, hy_val, _ = sess.run(
    [cost, hypothesis, train], feed_dict = {X: x_batch, Y:y_batch})
    
    if step % 10 == 0:
        print(step, "Cost: ", cost_val, '\nPrediction\n', hy_val)

coord.request_stop()
coord.join(threads)

# Ask my score
print("Your score will be ",
      sess.run(hypothesis, feed_dict={X: [[100, 70, 101]]}))

print("Other scores will be ",
      sess.run(hypothesis, feed_dict={X: [[60, 70, 110], [90, 100, 80]]}))


0 Cost:  17243.73 
Prediction
 [[16.325489]
 [30.821758]
 [24.44765 ]
 [25.234268]
 [22.200378]
 [16.325489]
 [30.821758]
 [24.44765 ]
 [25.234268]
 [22.200378]]
10 Cost:  27.594456 
Prediction
 [[144.09726]
 [184.42725]
 [175.78067]
 [142.40639]
 [108.56459]
 [144.09726]
 [184.42725]
 [175.78067]
 [142.40639]
 [108.56459]]
20 Cost:  24.87265 
Prediction
 [[145.6779  ]
 [186.28645 ]
 [177.63396 ]
 [143.81874 ]
 [109.592636]
 [145.6779  ]
 [186.28645 ]
 [177.63396 ]
 [143.81874 ]
 [109.592636]]
30 Cost:  24.701077 
Prediction
 [[145.7229 ]
 [186.2992 ]
 [177.66826]
 [143.82256]
 [109.58235]
 [145.7229 ]
 [186.2992 ]
 [177.66826]
 [143.82256]
 [109.58235]]
40 Cost:  24.531149 
Prediction
 [[145.7491 ]
 [186.28947]
 [177.68037]
 [143.80925]
 [109.55951]
 [145.7491 ]
 [186.28947]
 [177.68037]
 [143.80925]
 [109.55951]]
50 Cost:  24.362545 
Prediction
 [[145.77496]
 [186.27953]
 [177.69214]
 [143.79579]
 [109.53659]
 [145.77496]
 [186.27953]
 [177.69214]
 [143.79579]
 [109.53659]]
60 Cost: 

530 Cost:  17.614523 
Prediction
 [[146.90529 ]
 [185.84409 ]
 [178.20729 ]
 [143.20995 ]
 [108.531685]
 [146.90529 ]
 [185.84409 ]
 [178.20729 ]
 [143.20995 ]
 [108.531685]]
540 Cost:  17.4986 
Prediction
 [[146.92668]
 [185.83586]
 [178.21706]
 [143.19893]
 [108.51262]
 [146.92668]
 [185.83586]
 [178.21706]
 [143.19893]
 [108.51262]]
550 Cost:  17.38351 
Prediction
 [[146.94798]
 [185.82764]
 [178.22676]
 [143.18793]
 [108.49361]
 [146.94798]
 [185.82764]
 [178.22676]
 [143.18793]
 [108.49361]]
560 Cost:  17.26933 
Prediction
 [[146.9692 ]
 [185.81947]
 [178.23643]
 [143.177  ]
 [108.47466]
 [146.9692 ]
 [185.81947]
 [178.23643]
 [143.177  ]
 [108.47466]]
570 Cost:  17.156017 
Prediction
 [[146.99033 ]
 [185.81134 ]
 [178.24606 ]
 [143.1661  ]
 [108.455795]
 [146.99033 ]
 [185.81134 ]
 [178.24606 ]
 [143.1661  ]
 [108.455795]]
580 Cost:  17.04353 
Prediction
 [[147.01138]
 [185.8032 ]
 [178.25568]
 [143.15526]
 [108.437  ]
 [147.01138]
 [185.8032 ]
 [178.25568]
 [143.15526]
 [108.437

1040 Cost:  12.696356 
Prediction
 [[147.89636 ]
 [185.46188 ]
 [178.65936 ]
 [142.70139 ]
 [107.643745]
 [147.89636 ]
 [185.46188 ]
 [178.65936 ]
 [142.70139 ]
 [107.643745]]
1050 Cost:  12.617694 
Prediction
 [[147.91391]
 [185.45514]
 [178.66739]
 [142.69244]
 [107.62796]
 [147.91391]
 [185.45514]
 [178.66739]
 [142.69244]
 [107.62796]]
1060 Cost:  12.539662 
Prediction
 [[147.93137]
 [185.4484 ]
 [178.67535]
 [142.68353]
 [107.61223]
 [147.93137]
 [185.4484 ]
 [178.67535]
 [142.68353]
 [107.61223]]
1070 Cost:  12.46221 
Prediction
 [[147.94878 ]
 [185.44168 ]
 [178.6833  ]
 [142.67468 ]
 [107.596565]
 [147.94878 ]
 [185.44168 ]
 [178.6833  ]
 [142.67468 ]
 [107.596565]]
1080 Cost:  12.38532 
Prediction
 [[147.96611]
 [185.435  ]
 [178.69122]
 [142.66583]
 [107.58095]
 [147.96611]
 [185.435  ]
 [178.69122]
 [142.66583]
 [107.58095]]
1090 Cost:  12.309045 
Prediction
 [[147.98337]
 [185.42833]
 [178.6991 ]
 [142.65704]
 [107.56539]
 [147.98337]
 [185.42833]
 [178.6991 ]
 [142.65704]


1540 Cost:  9.41138 
Prediction
 [[148.69466]
 [185.15364]
 [179.02391]
 [142.2968 ]
 [106.92175]
 [148.69466]
 [185.15364]
 [179.02391]
 [142.2968 ]
 [106.92175]]
1550 Cost:  9.357576 
Prediction
 [[148.70908]
 [185.14809]
 [179.0305 ]
 [142.28955]
 [106.90864]
 [148.70908]
 [185.14809]
 [179.0305 ]
 [142.28955]
 [106.90864]]
1560 Cost:  9.304112 
Prediction
 [[148.72345]
 [185.14252]
 [179.03708]
 [142.2823 ]
 [106.89555]
 [148.72345]
 [185.14252]
 [179.03708]
 [142.2823 ]
 [106.89555]]
1570 Cost:  9.251059 
Prediction
 [[148.73778]
 [185.13698]
 [179.04361]
 [142.2751 ]
 [106.88252]
 [148.73778]
 [185.13698]
 [179.04361]
 [142.2751 ]
 [106.88252]]
1580 Cost:  9.19844 
Prediction
 [[148.75203 ]
 [185.13145 ]
 [179.05013 ]
 [142.26793 ]
 [106.869545]
 [148.75203 ]
 [185.13145 ]
 [179.05013 ]
 [142.26793 ]
 [106.869545]]
1590 Cost:  9.14616 
Prediction
 [[148.76627]
 [185.12598]
 [179.05663]
 [142.2608 ]
 [106.85661]
 [148.76627]
 [185.12598]
 [179.05663]
 [142.2608 ]
 [106.85661]]
160